import {useEffect,useState} from 'react';
import {api,dateText} from './api';
import type {Evidence,Review} from './types';
const labels:Record<string,string>={unknown:'待研判',escalation:'升级相关',sustain:'持续相关',easing:'缓和相关'};
export default function ReviewPanel({record,sid,onSaved}:{record:Evidence;sid:string;onSaved:(r:Evidence)=>void}){
  const [signal,setSignal]=useState(record.situation_signal),[reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[history,setHistory]=useState<Review[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{api<Review[]>(`/reviews/${record.id}?snapshot_id=${sid}`).then(setHistory).catch(()=>setMessage('修改记录加载失败，请重新打开详情'))},[record.id,sid]);
  return <section className="research-review"><h3>研究员研判</h3><p>确认或调整报道的态势分类；不代表报道事实已核验。仅适用于当前快照，地图与线索统计同步更新。</p><small>当前：{labels[record.situation_signal]} · {record.review?'研究员已确认':'自动分类，待人工复核'}</small><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await api<Evidence>(`/reviews/${record.id}?snapshot_id=${sid}`,{signal,reviewer,reason,version:record.review?.version||0});onSaved(r);setHistory(h=>[r.review!,...h]);setMessage('已保存研判，地图分类已更新');setReason('')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}><label>态势分类<select aria-label="研判分类" value={signal} onChange={e=>setSignal(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>研究员<input required maxLength={80} value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="填写姓名（本地署名）"/></label><label>判断依据<textarea required maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明确认或调整的证据与理由"/></label><button className="primary" disabled={busy||!reason.trim()||!reviewer.trim()}>{busy?'保存中…':signal===record.situation_signal?'确认当前分类':'保存分类调整'}</button></form>{message&&<p role="status">{message}</p>}<details><summary>修改记录（{history.length}）</summary>{history.map(r=><p key={r.version}><b>{labels[r.signal]} · {r.reviewer}</b><br/>{dateText(r.created_at)}<br/>{r.reason}</p>)}</details></section>
}
